### PR TITLE
Add APCA page

### PR DESCRIPTION
**Pull request by attitude**

### CODE REVIEW

**Review by jonasNobile — APPROVED** [review]

**Comment by VojtaStanek** [comment]
Reverted due to licensing concerns.

**Comment by Myndex** [comment]
Hi @VojtaStanek  What are the licensing concerns?

If I may, I suggest the APCA W3 repo which is the W3 license (essentially MIT).

It is on npm, ` npm i apca-w3 `

Also, Bridge-PCA is a drop-in replacement for WCAG 2's math. See that tool at https://www.myndex.com/BPCA/

Bridge-PCA is backwards compatible with WCAG 2, meaning it meets or exceeds WCAG 2 for compliance purposes, (including the areas where WCAG 2 rejects colors incorrectly). That said, Bridge-PCA is less flexible than the basic APCA guidelines.

Please let me know of any questions. The main repo discussion area is open with active discussions on APCA and related technologies: https://github.com/Myndex/SAPC-APCA/discussions

Also, there is this Linktree of all the main resources listed together:  https://linktr.ee/Myndex

Thank you!

Andy

**Comment by VojtaStanek** [comment]
Hi @Myndex 

Sorry for the late answer. On top of the [license file in acpa-w3 repository](https://github.com/Myndex/apca-w3/blob/master/LICENSE.md) there is the following summary:

> Files in this repository are licensed to the W3/AGWG under their cooperative agreement for **use with WCAG accessibility guidelines for web-based content only, and not for any other use**.

(emphasis mine)

This is a severe limitation which I am not sure if we comply with. And since I am not a lawyer I am taking a conservative approach of not using the package.

**Comment by Myndex** [comment]
Hi @VojtaStanek 

I'm sorry if there is confusion regarding this. the W3 license is essentially the MIT license. The scoping statement is because WCAG is scoped specific to web content.

What I want is that the disclaimer is affixed to code. Specifically, the W3 version of APCA should not be used for medical, clinical, transportation, military, or aerospace applications. So the license as written is simply to require providing that disclaimer.

This is in part because the code is still in a public beta stage, and it is important that any integration is maintained to update to important changes should they occur.

I hope this clarifies? Please let me know of further questions.

**Pull request merged**
