### PR TITLE
SEO guide

### PR DESCRIPTION
**Pull request by VojtaStanek**
- add seo guide
- update docusaurus

---
This change is [Reviewable](https://reviewable.io/reviews/contember/docs/61)

### CODE REVIEW

**Review by VojtaStanek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/docs/61)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @jonasNobile)

___
*[`docs/guides/seo.md` line 5 at r1](https://reviewable.io/reviews/contember/docs/61#-N3JhMGM8U_sn0Fgzsg2:-N3Jq8Ol0FDT6XuDc-GO:b-896fix) ([raw file](https://github.com/contember/docs/blob/9e39f233e60bce81dc210857fea17466a6faa82e/docs/guides/seo.md#L5)):*
> ```Markdown
> ---
> 
> In this guide, we will present one of the ways you can work with SEO fields in Contember. Here we will show how we have done it in our [headless CMS starter kit](https://github.com/contember/starter-kits/tree/main/headless-cms). You can take it as a continuation of the quickstart tutorial.
> ```

Done.
___
*[`docs/guides/seo.md` line 10 at r1](https://reviewable.io/reviews/contember/docs/61#-N3JhjjG7hGCk4gOM52X:-N3Jq7kw2WpPlISacwyo:b-896fix) ([raw file](https://github.com/contember/docs/blob/9e39f233e60bce81dc210857fea17466a6faa82e/docs/guides/seo.md#L10)):*
> ```Markdown
> ## 1. Schema definition
> 
> First, we have to define the schema. Here we we have chosen four fields we want to edit `title` (for `<title>` tag), `description` (for `<meta name="description" />`) and `ogTitle` and `ogDescription` (for `<meta property="og:title" />` and `<meta property="og:description " />` HTML Open Graph tags)
> ```

Done.
___
*[`docs/guides/seo.md` line 72 at r1](https://reviewable.io/reviews/contember/docs/61#-N3JjDN27kI8jQ5ntqiG:-N3Jq6nV9IrC59eoojfO:b-896fix) ([raw file](https://github.com/contember/docs/blob/9e39f233e60bce81dc210857fea17466a6faa82e/docs/guides/seo.md#L72)):*
> ```Markdown
> ```
> 
> To create migration for this we run `npm run contember migration:diff . add-seo` command and choose then choose `Yes and execute immediately` to create the migration file and execute it on our local machine.
> ```

Done.
___
*[`docs/guides/seo.md` line 97 at r1](https://reviewable.io/reviews/contember/docs/61#-N3JjXv89REBdyZ26DwM:-N3Jq6N-7AHvk1wmyh97:b-896fix) ([raw file](https://github.com/contember/docs/blob/9e39f233e60bce81dc210857fea17466a6faa82e/docs/guides/seo.md#L97)):*
> ```Markdown
> ```
> 
> Then we can then use the newly created component in existing administration pages like this:
> ```

Done.
___
*[`docs/guides/writing-components.md` line 72 at r1](https://reviewable.io/reviews/contember/docs/61#-N3Jm4O60ClP3gPcLFLx:-N3Jq59jEux0l3cUs71P:b-896fix) ([raw file](https://github.com/contember/docs/blob/9e39f233e60bce81dc210857fea17466a6faa82e/docs/guides/writing-components.md#L72)):*
> ```Markdown
> #### Example: ordinary components
> 
> If a component does not directly directly use data-binding, you don't have to worry about static render as Contember will always analyze its children.
> ```

Done.

**Review by jonasNobile — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/docs/61)* status: all files reviewed, 1 unresolved discussion (waiting on @VojtaStanek)

___
*[`docs/intro/quickstart.mdx` line 265 at r2](https://reviewable.io/reviews/contember/docs/61#-N3JsDu3B1qYlOsqNEGM:-N3JsDu3B1qYlOsqNEGN:undefined) ([raw file](https://github.com/contember/docs/blob/4e92f4834d533104bbae0bf556f26c0bf961fd7d/docs/intro/quickstart.mdx#L265)):*
> ```Markdown
> ## Next steps
> 
> - You can [deploy your project do Contember Cloud](/guides/deploy-contember.md).
> ```





_Suggestion:_
```Markdown
project to Contember Cloud
```

**Review by VojtaStanek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/docs/61)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @jonasNobile)

___
*[`docs/intro/quickstart.mdx` line 265 at r2](https://reviewable.io/reviews/contember/docs/61#-N3JsDu3B1qYlOsqNEGM:-N3JtblvETjcUsBM8dkd:b-896fix) ([raw file](https://github.com/contember/docs/blob/4e92f4834d533104bbae0bf556f26c0bf961fd7d/docs/intro/quickstart.mdx#L265)):*
> ```Markdown
> ## Next steps
> 
> - You can [deploy your project do Contember Cloud](/guides/deploy-contember.md).
> ```

Done.

**Review by jonasNobile — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/docs/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @VojtaStanek)

**Pull request merged**
