### PR TITLE
New deployment guides

### PR DESCRIPTION
**Pull request by VojtaStanek**
This change is [Reviewable](https://reviewable.io/reviews/contember/docs/55)

### CODE REVIEW

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/docs/55)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JanTvrdik and @VojtaStanek)

___
*[docs/guides/deploy-contember.md, line 9 at r1](https://reviewable.io/reviews/contember/docs/55#-N0Gk0ge-VPDMF1-J0bs:-N0Gk0ge-VPDMF1-J0bt:b13bh10) ([raw file](https://github.com/contember/docs/blob/2dfb0ddbc570d714d210c2607e4f621963aff7c0/docs/guides/deploy-contember.md#L9)):*
> ```Markdown
> 
> :::tip
> If you want to manage your own cloud on your infrastructure [contact us](https://www.contember.com/contact) for more information and licensing options.
> ```

That makes it sound like self hosting always requires a licese, even though it's not usually required.

**Review by VojtaStanek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/docs/55)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JanTvrdik)

___
*[docs/guides/deploy-contember.md, line 9 at r1](https://reviewable.io/reviews/contember/docs/55#-N0Gk0ge-VPDMF1-J0bs:-N0GuFKZAHOqrR1km1zq:b-7mhi0a) ([raw file](https://github.com/contember/docs/blob/2dfb0ddbc570d714d210c2607e4f621963aff7c0/docs/guides/deploy-contember.md#L9)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

That makes it sound like self hosting always requires a licese, even though it's not usually required.
</blockquote></details>

Done. Removed it.

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/docs/55)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @JanTvrdik and @VojtaStanek)

___
*[docs/guides/self-hosted-contember.md, line 12 at r3](https://reviewable.io/reviews/contember/docs/55#-N0GvqFQAyRW3EwLIHs8:-N0GvqFQAyRW3EwLIHs9:bp847fl) ([raw file](https://github.com/contember/docs/blob/844789cf020313ed12bfece9d5fc225cbf0a48ec/docs/guides/self-hosted-contember.md#L12)):*
> ```Markdown
> ## What you'll need
> 
> 1. PostgreSQL database (like [AWS RDS for PostgreSQL](https://aws.amazon.com/rds/postgresql/), [DigitalOcean Managed Database](https://www.digitalocean.com/products/managed-databases/))
> ```

like -> e.g.
this is actually required
___
*[docs/guides/self-hosted-contember.md, line 13 at r3](https://reviewable.io/reviews/contember/docs/55#-N0GvyN_8RMhxoejfBMN:-N0GvyN_8RMhxoejfBMO:b-pks9ug) ([raw file](https://github.com/contember/docs/blob/844789cf020313ed12bfece9d5fc225cbf0a48ec/docs/guides/self-hosted-contember.md#L13)):*
> ```Markdown
> 
> 1. PostgreSQL database (like [AWS RDS for PostgreSQL](https://aws.amazon.com/rds/postgresql/), [DigitalOcean Managed Database](https://www.digitalocean.com/products/managed-databases/))
> 1. S3-compatible storage for file uploads (like [AWS S3](https://aws.amazon.com/s3/), [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/), [MinIO](https://min.io/), [CEPH](https://ceph.io/), [Zenko CloudServer](https://www.zenko.io/cloudserver/))
> ```

like -> e.g.
this is required only when uploading files
___
*[docs/guides/self-hosted-contember.md, line 14 at r3](https://reviewable.io/reviews/contember/docs/55#-N0GwBFV00iFEvgb1yuJ:-N0GwBFV00iFEvgb1yuK:bny405z) ([raw file](https://github.com/contember/docs/blob/844789cf020313ed12bfece9d5fc225cbf0a48ec/docs/guides/self-hosted-contember.md#L14)):*
> ```Markdown
> 1. PostgreSQL database (like [AWS RDS for PostgreSQL](https://aws.amazon.com/rds/postgresql/), [DigitalOcean Managed Database](https://www.digitalocean.com/products/managed-databases/))
> 1. S3-compatible storage for file uploads (like [AWS S3](https://aws.amazon.com/s3/), [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/), [MinIO](https://min.io/), [CEPH](https://ceph.io/), [Zenko CloudServer](https://www.zenko.io/cloudserver/))
> 1. SMTP server to send emails from
> ```

this is required only when sending emails
___
*[docs/guides/self-hosted-contember.md, line 15 at r3](https://reviewable.io/reviews/contember/docs/55#-N0GwDek0Uxkk1ZlqgxW:-N0GwDek0Uxkk1ZlqgxX:bwtnrba) ([raw file](https://github.com/contember/docs/blob/844789cf020313ed12bfece9d5fc225cbf0a48ec/docs/guides/self-hosted-contember.md#L15)):*
> ```Markdown
> 1. S3-compatible storage for file uploads (like [AWS S3](https://aws.amazon.com/s3/), [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/), [MinIO](https://min.io/), [CEPH](https://ceph.io/), [Zenko CloudServer](https://www.zenko.io/cloudserver/))
> 1. SMTP server to send emails from
> 1. Some way to run Docker image.
> ```

this is required only when using docker images; Contember can also be without much trouble run without Docker with just node
that being said we don't officialy support running engine without Docker
___
*[docs/guides/self-hosted-contember.md, line 60 at r3](https://reviewable.io/reviews/contember/docs/55#-N0GxHuw5-w0AGzDQWaD:-N0GxHuw5-w0AGzDQWaE:b-8ce7s4) ([raw file](https://github.com/contember/docs/blob/844789cf020313ed12bfece9d5fc225cbf0a48ec/docs/guides/self-hosted-contember.md#L60)):*
> ```Markdown
> DEFAULT_DB_PASSWORD: "postgres"
> DEFAULT_DB_SSL: "true"
> TENANT_DB_NAME: "tenant" # Name of tenant database - see first step
> ```

should be recommend by default to use single database, e.g. use `DEFAULT_DB_NAME` instead?
___
*[docs/guides/self-hosted-contember.md, line 75 at r3](https://reviewable.io/reviews/contember/docs/55#-N0Gx4KTAqsN7_K2fBU_:-N0Gx4KTAqsN7_K2fBUa:bx1kluh) ([raw file](https://github.com/contember/docs/blob/844789cf020313ed12bfece9d5fc225cbf0a48ec/docs/guides/self-hosted-contember.md#L75)):*
> ```Markdown
> ```
> 
> HTTP server should start on specified port. You can add load-balancer in front of the app. The container is stateless and therefor completely scalable.
> ```

completely -> horizonally

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/docs/55)* status: all files reviewed, 2 unresolved discussions (waiting on @VojtaStanek)

___
*[`docs/guides/self-hosted-contember.md` line 93 at r4](https://reviewable.io/reviews/contember/docs/55#-N0bRnHR5wnYs8cMQklh:-N0bRnHR5wnYs8cMQkli:b-k6k0k2) ([raw file](https://github.com/contember/docs/blob/d08ec90793267bccaff158aa6eaddd3b3b80b1d6/docs/guides/self-hosted-contember.md#L93)):*
> ```Markdown
> import '@contember/admin/style.css'
> import { Layout } from './components/Layout'
> import '@contember/admin/style.css'
> ```

duplicate line
___
*[`docs/guides/self-hosted-contember.md` line 113 at r4](https://reviewable.io/reviews/contember/docs/55#-N0bS431EDRT23Njnb8X:-N0bS-8f4-0HTWJcrOCV:bf5ojoj) ([raw file](https://github.com/contember/docs/blob/d08ec90793267bccaff158aa6eaddd3b3b80b1d6/docs/guides/self-hosted-contember.md#L113)):*
> ```Markdown
> 	runReactApp(
> 		<ApplicationEntrypoint
> 			basePath={'./'}
> ```

I feel like this should not work. Or at least not reliably. BasePath should be `/{projectSlug}`.

**Review by VojtaStanek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/docs/55)* status: all files reviewed, 2 unresolved discussions (waiting on @JanTvrdik and @VojtaStanek)

___
*[`docs/guides/self-hosted-contember.md` line 113 at r4](https://reviewable.io/reviews/contember/docs/55#-N0bS431EDRT23Njnb8X:-N0e6C2_4p7m2p7O10mV:bkahpuh) ([raw file](https://github.com/contember/docs/blob/d08ec90793267bccaff158aa6eaddd3b3b80b1d6/docs/guides/self-hosted-contember.md#L113)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

I feel like this should not work. Or at least not reliably. BasePath should be `/{projectSlug}`.
</blockquote></details>

Yes: https://github.com/contember/admin/blob/main/packages/admin/src/components/ApplicationEntrypoint.tsx#L34-L36

**Review by VojtaStanek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/docs/55)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @JanTvrdik)

___
*[`docs/guides/self-hosted-contember.md` line 93 at r4](https://reviewable.io/reviews/contember/docs/55#-N0bRnHR5wnYs8cMQklh:-N0eC1Q9B_ThPp0OOWX0:b-896fix) ([raw file](https://github.com/contember/docs/blob/d08ec90793267bccaff158aa6eaddd3b3b80b1d6/docs/guides/self-hosted-contember.md#L93)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

duplicate line
</blockquote></details>

Done.

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/docs/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @VojtaStanek)

**Pull request merged**
